#pragma once

#define ICON_ALBUM         "󰀥"
#define ICON_ANY           ""
#define ICON_ARTIST        ""
#define ICON_ARTIST_ALBUM  ""
#define ICON_COMMENT       ""
#define ICON_COMPOSER      "󱟄"
#define ICON_CONSUME       ""
#define ICON_CROSSFADE     "󰥛"
#define ICON_DATE          ""
#define ICON_DIRECTORY     ""
#define ICON_DOT           ""
#define ICON_EDIT          ""
#define ICON_FILE          ""
#define ICON_GENRE         "󱑽"
#define ICON_PERFORMER     "󰍰"
#define ICON_PLAYLIST      "󰲹"
#define ICON_RANDOM        ""
#define ICON_REPEAT        "󰑖"
#define ICON_REPEAT_SINGLE "󰑘"
#define ICON_SINGLE        "󰬺"
#define ICON_SONG          ""
#define ICON_TAG           "󰽭"
#define ICON_TITLE         "󰊄"
#define ICON_UPDATE        ""
